# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form_agregar_unidad_educativa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_Unidad_Educativa(object):
    def setupUi(self, add_Unidad_Educativa):
        add_Unidad_Educativa.setObjectName("add_Unidad_Educativa")
        add_Unidad_Educativa.resize(600, 160)
        add_Unidad_Educativa.setMinimumSize(QtCore.QSize(600, 160))
        add_Unidad_Educativa.setMaximumSize(QtCore.QSize(600, 160))
        add_Unidad_Educativa.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_save = QtWidgets.QPushButton(add_Unidad_Educativa)
        self.pushButton_save.setGeometry(QtCore.QRect(170, 100, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_cancel = QtWidgets.QPushButton(add_Unidad_Educativa)
        self.pushButton_cancel.setGeometry(QtCore.QRect(310, 100, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.formLayoutWidget = QtWidgets.QWidget(add_Unidad_Educativa)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 581, 52))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_name_unidad_educativa = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_name_unidad_educativa.setFont(font)
        self.lineEdit_name_unidad_educativa.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.lineEdit_name_unidad_educativa.setObjectName("lineEdit_name_unidad_educativa")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_name_unidad_educativa)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(56, 71, 151);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)

        self.retranslateUi(add_Unidad_Educativa)
        QtCore.QMetaObject.connectSlotsByName(add_Unidad_Educativa)

    def retranslateUi(self, add_Unidad_Educativa):
        _translate = QtCore.QCoreApplication.translate
        add_Unidad_Educativa.setWindowTitle(_translate("add_Unidad_Educativa", "Agregar Unidad Educativa"))
        self.pushButton_save.setText(_translate("add_Unidad_Educativa", "Guardar"))
        self.pushButton_cancel.setText(_translate("add_Unidad_Educativa", "Cerrar"))
        self.label.setText(_translate("add_Unidad_Educativa", "Nombre Unidad Educativa"))
