# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form_agregar_discapacidad.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Agregar_Discapacidades(object):
    def setupUi(self, Agregar_Discapacidades):
        Agregar_Discapacidades.setObjectName("Agregar_Discapacidades")
        Agregar_Discapacidades.resize(645, 160)
        Agregar_Discapacidades.setMinimumSize(QtCore.QSize(645, 160))
        Agregar_Discapacidades.setMaximumSize(QtCore.QSize(645, 160))
        Agregar_Discapacidades.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_save = QtWidgets.QPushButton(Agregar_Discapacidades)
        self.pushButton_save.setGeometry(QtCore.QRect(220, 100, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_close = QtWidgets.QPushButton(Agregar_Discapacidades)
        self.pushButton_close.setGeometry(QtCore.QRect(340, 100, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}")
        self.pushButton_close.setObjectName("pushButton_close")
        self.formLayoutWidget = QtWidgets.QWidget(Agregar_Discapacidades)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 40, 601, 52))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.line_discapacidad = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.line_discapacidad.setFont(font)
        self.line_discapacidad.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.line_discapacidad.setObjectName("line_discapacidad")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_discapacidad)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(56, 71, 151);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)

        self.retranslateUi(Agregar_Discapacidades)
        QtCore.QMetaObject.connectSlotsByName(Agregar_Discapacidades)

    def retranslateUi(self, Agregar_Discapacidades):
        _translate = QtCore.QCoreApplication.translate
        Agregar_Discapacidades.setWindowTitle(_translate("Agregar_Discapacidades", "Agregar Discapacidad"))
        self.pushButton_save.setText(_translate("Agregar_Discapacidades", "Guardar"))
        self.pushButton_close.setText(_translate("Agregar_Discapacidades", "Cancelar"))
        self.label.setText(_translate("Agregar_Discapacidades", "Nombre Discapacidad"))
