# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\agregar_est.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_student(object):
    def setupUi(self, add_student):
        add_student.setObjectName("add_student")
        add_student.resize(1280, 720)
        add_student.setMinimumSize(QtCore.QSize(1280, 720))
        add_student.setMaximumSize(QtCore.QSize(1280, 720))
        add_student.setBaseSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        add_student.setFont(font)
        self.pushButton = QtWidgets.QPushButton(add_student)
        self.pushButton.setGeometry(QtCore.QRect(90, 330, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(add_student)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 330, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(add_student)
        self.lineEdit.setGeometry(QtCore.QRect(180, 90, 291, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(add_student)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 130, 291, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(add_student)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 170, 291, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(add_student)
        self.label.setGeometry(QtCore.QRect(50, 100, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(add_student)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(add_student)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 61, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(add_student)
        QtCore.QMetaObject.connectSlotsByName(add_student)

    def retranslateUi(self, add_student):
        _translate = QtCore.QCoreApplication.translate
        add_student.setWindowTitle(_translate("add_student", "Form"))
        self.pushButton.setText(_translate("add_student", "Guardar"))
        self.pushButton_2.setText(_translate("add_student", "Cancelar"))
        self.label.setText(_translate("add_student", "Cedula"))
        self.label_2.setText(_translate("add_student", "Apellido"))
        self.label_3.setText(_translate("add_student", "Nombre"))
