# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\confirm_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_confirm_dialog(object):
    def setupUi(self, confirm_dialog):
        confirm_dialog.setObjectName("confirm_dialog")
        confirm_dialog.resize(450, 100)
        confirm_dialog.setMinimumSize(QtCore.QSize(450, 100))
        confirm_dialog.setMaximumSize(QtCore.QSize(450, 100))
        confirm_dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_1 = QtWidgets.QLabel(confirm_dialog)
        self.label_1.setGeometry(QtCore.QRect(20, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.pushButton_yes = QtWidgets.QPushButton(confirm_dialog)
        self.pushButton_yes.setGeometry(QtCore.QRect(120, 60, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.pushButton_yes.setFont(font)
        self.pushButton_yes.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}\n"
"")
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.pushButton_no = QtWidgets.QPushButton(confirm_dialog)
        self.pushButton_no.setGeometry(QtCore.QRect(230, 60, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.pushButton_no.setFont(font)
        self.pushButton_no.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}\n"
"")
        self.pushButton_no.setObjectName("pushButton_no")
        self.label_message = QtWidgets.QLabel(confirm_dialog)
        self.label_message.setGeometry(QtCore.QRect(110, 20, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_message.setFont(font)
        self.label_message.setObjectName("label_message")

        self.retranslateUi(confirm_dialog)
        QtCore.QMetaObject.connectSlotsByName(confirm_dialog)

    def retranslateUi(self, confirm_dialog):
        _translate = QtCore.QCoreApplication.translate
        confirm_dialog.setWindowTitle(_translate("confirm_dialog", "Mensaje de confirmacion"))
        self.label_1.setText(_translate("confirm_dialog", "Mensaje: "))
        self.pushButton_yes.setText(_translate("confirm_dialog", "SI"))
        self.pushButton_no.setText(_translate("confirm_dialog", "NO"))
        self.label_message.setText(_translate("confirm_dialog", "Seguro que desea eliminar?"))
