# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form_modulo_vumetro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_modulo_vumetro(object):
    def setupUi(self, Form_modulo_vumetro):
        Form_modulo_vumetro.setObjectName("Form_modulo_vumetro")
        Form_modulo_vumetro.resize(1280, 720)
        Form_modulo_vumetro.setMinimumSize(QtCore.QSize(1280, 720))
        Form_modulo_vumetro.setMaximumSize(QtCore.QSize(1280, 720))
        Form_modulo_vumetro.setBaseSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Form_modulo_vumetro.setFont(font)
        Form_modulo_vumetro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_conn_status = QtWidgets.QLabel(Form_modulo_vumetro)
        self.label_conn_status.setGeometry(QtCore.QRect(1150, 680, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_conn_status.setFont(font)
        self.label_conn_status.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_conn_status.setObjectName("label_conn_status")
        self.label_logo2 = QtWidgets.QLabel(Form_modulo_vumetro)
        self.label_logo2.setGeometry(QtCore.QRect(1150, 0, 130, 130))
        self.label_logo2.setText("")
        self.label_logo2.setObjectName("label_logo2")
        self.label = QtWidgets.QLabel(Form_modulo_vumetro)
        self.label.setGeometry(QtCore.QRect(470, 20, 350, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(56, 71, 151);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textEdit_instructions = QtWidgets.QTextEdit(Form_modulo_vumetro)
        self.textEdit_instructions.setGeometry(QtCore.QRect(40, 380, 451, 261))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.textEdit_instructions.setFont(font)
        self.textEdit_instructions.setObjectName("textEdit_instructions")
        self.label_logo1 = QtWidgets.QLabel(Form_modulo_vumetro)
        self.label_logo1.setGeometry(QtCore.QRect(0, 0, 260, 150))
        self.label_logo1.setText("")
        self.label_logo1.setObjectName("label_logo1")
        self.label_module_image = QtWidgets.QLabel(Form_modulo_vumetro)
        self.label_module_image.setGeometry(QtCore.QRect(50, 150, 441, 191))
        self.label_module_image.setText("")
        self.label_module_image.setObjectName("label_module_image")
        self.label_2 = QtWidgets.QLabel(Form_modulo_vumetro)
        self.label_2.setGeometry(QtCore.QRect(40, 360, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(56, 71, 151);")
        self.label_2.setObjectName("label_2")
        self.label_text_status = QtWidgets.QLabel(Form_modulo_vumetro)
        self.label_text_status.setGeometry(QtCore.QRect(940, 680, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_text_status.setFont(font)
        self.label_text_status.setObjectName("label_text_status")
        self.pushButton_start = QtWidgets.QPushButton(Form_modulo_vumetro)
        self.pushButton_start.setGeometry(QtCore.QRect(710, 620, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}\n"
"QPushButton:disabled {\n"
"background-color:#A0A0A0;\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.label_textlevel = QtWidgets.QLabel(Form_modulo_vumetro)
        self.label_textlevel.setGeometry(QtCore.QRect(810, 560, 100, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_textlevel.setFont(font)
        self.label_textlevel.setStyleSheet("color: rgb(56, 71, 151);")
        self.label_textlevel.setObjectName("label_textlevel")
        self.label_level = QtWidgets.QLabel(Form_modulo_vumetro)
        self.label_level.setGeometry(QtCore.QRect(920, 560, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_level.setFont(font)
        self.label_level.setText("")
        self.label_level.setObjectName("label_level")
        self.pushButton_stop = QtWidgets.QPushButton(Form_modulo_vumetro)
        self.pushButton_stop.setGeometry(QtCore.QRect(830, 620, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}\n"
"QPushButton:disabled {\n"
"background-color:#A0A0A0;\n"
"}")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_save = QtWidgets.QPushButton(Form_modulo_vumetro)
        self.pushButton_save.setGeometry(QtCore.QRect(950, 620, 110, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}\n"
"QPushButton:disabled {\n"
"background-color:#A0A0A0;\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.plot_widget = QtWidgets.QWidget(Form_modulo_vumetro)
        self.plot_widget.setGeometry(QtCore.QRect(520, 150, 711, 401))
        self.plot_widget.setStyleSheet("border: 2px solid #384797;\n"
"")
        self.plot_widget.setObjectName("plot_widget")
        self.label_reading_data = QtWidgets.QLabel(Form_modulo_vumetro)
        self.label_reading_data.setGeometry(QtCore.QRect(830, 590, 120, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_reading_data.setFont(font)
        self.label_reading_data.setStyleSheet("color: rgb(56, 71, 151);")
        self.label_reading_data.setObjectName("label_reading_data")

        self.retranslateUi(Form_modulo_vumetro)
        QtCore.QMetaObject.connectSlotsByName(Form_modulo_vumetro)

    def retranslateUi(self, Form_modulo_vumetro):
        _translate = QtCore.QCoreApplication.translate
        Form_modulo_vumetro.setWindowTitle(_translate("Form_modulo_vumetro", "Modulo Vumetro"))
        self.label_conn_status.setText(_translate("Form_modulo_vumetro", "Conectado"))
        self.label.setText(_translate("Form_modulo_vumetro", "MODULO: VUMETRO"))
        self.textEdit_instructions.setHtml(_translate("Form_modulo_vumetro", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans\',\'Arial\',\'sans-serif\'; font-size:8pt; color:#000000; background-color:#ffffff;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean consectetur tristique purus vel tristique. Aliquam mattis purus ultricies, lobortis lacus at, vestibulum velit. Nam nulla ligula, sollicitudin consectetur porta blandit, fringilla a quam. Nulla suscipit mauris at semper tempor. Aliquam vestibulum eu nisl a ornare. Duis nec interdum leo. Mauris nec laoreet lectus. Nullam pharetra, risus vitae aliquet malesuada, arcu nibh malesuada erat, quis viverra dui sem et nisl. Donec eu felis finibus, maximus nulla venenatis, pulvinar mi. Donec at hendrerit ex. Donec nec turpis sed leo suscipit vulputate id ut ex. Integer ornare lorem dui, quis luctus risus maximus ac.</span></p></body></html>"))
        self.label_2.setText(_translate("Form_modulo_vumetro", "Instrucciones"))
        self.label_text_status.setText(_translate("Form_modulo_vumetro", "Estado Conexion Bluetooth: "))
        self.pushButton_start.setText(_translate("Form_modulo_vumetro", "Iniciar"))
        self.label_textlevel.setText(_translate("Form_modulo_vumetro", "Nivel Maximo:"))
        self.pushButton_stop.setText(_translate("Form_modulo_vumetro", "Detener"))
        self.pushButton_save.setText(_translate("Form_modulo_vumetro", "Guardar"))
        self.label_reading_data.setText(_translate("Form_modulo_vumetro", "Leyendo datos..."))
