# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form_seleccion_modulos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_seleccion_modulos(object):
    def setupUi(self, Form_seleccion_modulos):
        Form_seleccion_modulos.setObjectName("Form_seleccion_modulos")
        Form_seleccion_modulos.resize(1280, 720)
        Form_seleccion_modulos.setMinimumSize(QtCore.QSize(1280, 720))
        Form_seleccion_modulos.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Form_seleccion_modulos.setFont(font)
        Form_seleccion_modulos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Form_seleccion_modulos)
        self.label.setGeometry(QtCore.QRect(504, 40, 272, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(56, 71, 151);")
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(Form_seleccion_modulos)
        self.formLayoutWidget.setGeometry(QtCore.QRect(390, 130, 491, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_apellidos = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_apellidos.setFont(font)
        self.label_apellidos.setObjectName("label_apellidos")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_apellidos)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_nombres = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_nombres.setFont(font)
        self.label_nombres.setObjectName("label_nombres")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_nombres)
        self.label_cedula = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_cedula.setFont(font)
        self.label_cedula.setObjectName("label_cedula")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_cedula)
        self.label_8 = QtWidgets.QLabel(Form_seleccion_modulos)
        self.label_8.setGeometry(QtCore.QRect(530, 90, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(56, 71, 151);")
        self.label_8.setObjectName("label_8")
        self.pushButton_module_grafomotricidad = QtWidgets.QPushButton(Form_seleccion_modulos)
        self.pushButton_module_grafomotricidad.setGeometry(QtCore.QRect(280, 290, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_module_grafomotricidad.setFont(font)
        self.pushButton_module_grafomotricidad.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}")
        self.pushButton_module_grafomotricidad.setObjectName("pushButton_module_grafomotricidad")
        self.pushButton_module_pictograma = QtWidgets.QPushButton(Form_seleccion_modulos)
        self.pushButton_module_pictograma.setGeometry(QtCore.QRect(740, 290, 261, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_module_pictograma.setFont(font)
        self.pushButton_module_pictograma.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}")
        self.pushButton_module_pictograma.setObjectName("pushButton_module_pictograma")
        self.pushButton_module_vumetro = QtWidgets.QPushButton(Form_seleccion_modulos)
        self.pushButton_module_vumetro.setGeometry(QtCore.QRect(280, 440, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_module_vumetro.setFont(font)
        self.pushButton_module_vumetro.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}")
        self.pushButton_module_vumetro.setObjectName("pushButton_module_vumetro")
        self.pushButton_module_iluminacion = QtWidgets.QPushButton(Form_seleccion_modulos)
        self.pushButton_module_iluminacion.setGeometry(QtCore.QRect(740, 440, 261, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_module_iluminacion.setFont(font)
        self.pushButton_module_iluminacion.setStyleSheet("QPushButton {\n"
"   border-radius: 10px;\n"
"    background-color: rgb(56, 71, 151);\n"
"  color: rgb(255, 255, 255); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid;\n"
"}")
        self.pushButton_module_iluminacion.setObjectName("pushButton_module_iluminacion")
        self.label_logo_1 = QtWidgets.QLabel(Form_seleccion_modulos)
        #self.label_logo_1.setGeometry(QtCore.QRect(0, 0, 161, 131))
        self.label_logo_1.setGeometry(QtCore.QRect(0, 0, 270, 200))
        self.label_logo_1.setText("")
        self.label_logo_1.setObjectName("label_logo_1")
        self.label_logo_2 = QtWidgets.QLabel(Form_seleccion_modulos)
        self.label_logo_2.setGeometry(QtCore.QRect(1080, 0, 200,200))
        self.label_logo_2.setText("")
        self.label_logo_2.setObjectName("label_logo_2")
        self.label_bluetooth_status = QtWidgets.QLabel(Form_seleccion_modulos)
        self.label_bluetooth_status.setGeometry(QtCore.QRect(1000, 680, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_bluetooth_status.setFont(font)
        self.label_bluetooth_status.setText("")
        self.label_bluetooth_status.setObjectName("label_bluetooth_status")
        self.label_3 = QtWidgets.QLabel(Form_seleccion_modulos)
        self.label_3.setGeometry(QtCore.QRect(990, 640, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_com_port = QtWidgets.QLineEdit(Form_seleccion_modulos)
        self.lineEdit_com_port.setGeometry(QtCore.QRect(1080, 635, 81, 27))
        self.lineEdit_com_port.setMinimumSize(QtCore.QSize(81, 27))
        self.lineEdit_com_port.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lineEdit_com_port.setFont(font)
        self.lineEdit_com_port.setObjectName("lineEdit_com_port")
        self.label_5 = QtWidgets.QLabel(Form_seleccion_modulos)
        self.label_5.setGeometry(QtCore.QRect(990, 610, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form_seleccion_modulos)
        QtCore.QMetaObject.connectSlotsByName(Form_seleccion_modulos)

    def retranslateUi(self, Form_seleccion_modulos):
        _translate = QtCore.QCoreApplication.translate
        Form_seleccion_modulos.setWindowTitle(_translate("Form_seleccion_modulos", "Seleccion Modulos"))
        self.label.setText(_translate("Form_seleccion_modulos", "Seleccion de Modulos"))
        self.label_2.setText(_translate("Form_seleccion_modulos", "CEDULA:"))
        self.label_4.setText(_translate("Form_seleccion_modulos", "APELLIDOS:"))
        self.label_apellidos.setText(_translate("Form_seleccion_modulos", "TextLabel"))
        self.label_6.setText(_translate("Form_seleccion_modulos", "NOMBRES:"))
        self.label_nombres.setText(_translate("Form_seleccion_modulos", "TextLabel"))
        self.label_cedula.setText(_translate("Form_seleccion_modulos", "TextLabel"))
        self.label_8.setText(_translate("Form_seleccion_modulos", "INFORMACION ESTUDIANTE"))
        self.pushButton_module_grafomotricidad.setText(_translate("Form_seleccion_modulos", "Modulo: Grafomotricidad"))
        self.pushButton_module_pictograma.setText(_translate("Form_seleccion_modulos", "Modulo: Panel de Pictogramas"))
        self.pushButton_module_vumetro.setText(_translate("Form_seleccion_modulos", "Modulo: Vumetro"))
        self.pushButton_module_iluminacion.setText(_translate("Form_seleccion_modulos", "Modulo: Iluminacion"))
        self.label_3.setText(_translate("Form_seleccion_modulos", "PUERTO :"))
        self.lineEdit_com_port.setText(_translate("Form_seleccion_modulos", "COM6"))
        self.label_5.setText(_translate("Form_seleccion_modulos", "Conexion Bluetooth:"))
